### ISSUE TITLE
vote strategy？

### ISSUE THREAD

**Issue by swzaaaaaaa** [tiangexiang/CurveNet#13]
你好，请问，这个投票测试是什么意思，为什么会比最好的模型的还要高？

**Comment by tiangexiang** [comment]
Hi, the voting strategy was first introduced in RSCNN (https://arxiv.org/abs/1904.07601). That is, given the best performing model, during inference, input point clouds are randomly augmented (jittered or scaled) for k different times, and the prediction for this single input batch is the average of the k runs.
Since such a strategy heavily relies on randomness, both RSCNN and our CurveNet repeat the voting process 300 times and then pick the best result to report.

**Comment by swzaaaaaaa** [comment]
Fine，thanks。

**Comment by tiangexiang** [comment]
Closing for now :)
