### ISSUE TITLE
Questions about gumbel-softmax without gumbel sampling

### ISSUE THREAD

**Issue by yifliu3** [tiangexiang/CurveNet#14]
Thanks for your excellent work!
While reading through your paper I find that you've mentioned Gumbel samplings are disabled for avoiding any randomness, and from my view, Gubel-softmax without Gumbel sampling is simply equivalent to the softmax function with annealing coefficient. I'm wondering if my understanding is correct,  thanks.

**Comment by tiangexiang** [comment]
Hi, thanks for your interest! 
Actually, for 'Gumbel-softmax', we referred to their re-parametrization trick instead of the entire Gumbel-softmax. That is, we only want a one-hot (argmax equivalent) output during forward, and smooth gradients (plain softmax equivalent) during backward. 
You can have a look at our implementations: https://github.com/tiangexiang/CurveNet/blob/main/core/models/walk.py#L23 for details :)

**Comment by yifliu3** [comment]
I see, thanks for your kind reply!
